services:
  # Our PostgreSQL database
  db:
    container_name: ticket-db
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: rony010
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ticket-network

  # Database management interface
  adminer:
    container_name: ticket-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    networks:
      - ticket-network

  keycloak:
    container_name: ticket-keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - ticket-network
    command:
      - start-dev
      - --db=dev-file

volumes:
  keycloak-data:
    driver: local
  postgres-data:
    driver: local

networks:
  ticket-network:
    driver: bridge
